// @flow

const DO_REFRESH = 'DO_REFRESH';
const DONOT_REFRESH = 'DONOT_REFRESH';
const GETUSER_FAIL = 'GETUSER_FAIL';
const GETUSER_PENDING = 'GETUSER_PENDING';
const GETUSER_SUCCESS = 'GETUSER_SUCCESS';
const GOOGLE_LOGIN_PENDING = 'GOOGLE_LOGIN_PENDING';
const INTRO = 'INTRO';
const LOGIN_FAIL = 'LOGIN_FAIL';
const LOGIN_PENDING = 'LOGIN_PENDING';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGOUT = 'LOGOUT';
const RELOAD_FAIL = 'RELOAD_FAIL';
const RELOAD_PENDING = 'RELOAD_PENDING';
const RELOAD_SUCCESS = 'RELOAD_SUCCESS';
const SIGNUP_FAIL = 'SIGNUP_FAIL';
const SIGNUP_PENDING = 'SIGNUP_PENDING';
const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export {
  DO_REFRESH,
  DONOT_REFRESH,
  GETUSER_FAIL,
  GETUSER_PENDING,
  GETUSER_SUCCESS,
  GOOGLE_LOGIN_PENDING,
  INTRO,
  LOGIN_FAIL,
  LOGIN_PENDING,
  LOGIN_SUCCESS,
  LOGOUT,
  RELOAD_FAIL,
  RELOAD_PENDING,
  RELOAD_SUCCESS,
  SIGNUP_FAIL,
  SIGNUP_PENDING,
  SIGNUP_SUCCESS,
};
