// @flow

const LOGIN_PENDING = 'LOGIN_PENDING';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAIL = 'LOGIN_FAIL';
const GOOGLE_LOGIN_PENDING = 'GOOGLE_LOGIN_PENDING';
const SIGNUP_PENDING = 'SIGNUP_PENDING';
const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
const SIGNUP_FAIL = 'SIGNUP_FAIL';
const LOGOUT = 'LOGOUT';
const GETUSER_PENDING = 'GETUSER_PENDING';
const GETUSER_SUCCESS = 'GETUSER_SUCCESS';
const GETUSER_FAIL = 'GETUSER_FAIL';
const DO_REFRESH = 'DO_REFRESH';
const DONOT_REFRESH = 'DONOT_REFRESH';
const RELOAD_SUCCESS = 'RELOAD_SUCCESS';
const RELOAD_FAIL = 'RELOAD_FAIL';

export {
  LOGIN_PENDING,
  LOGIN_SUCCESS,
  LOGIN_FAIL,
  GOOGLE_LOGIN_PENDING,
  SIGNUP_PENDING,
  SIGNUP_SUCCESS,
  SIGNUP_FAIL,
  LOGOUT,
  GETUSER_PENDING,
  GETUSER_SUCCESS,
  GETUSER_FAIL,
  DO_REFRESH,
  DONOT_REFRESH,
  RELOAD_SUCCESS,
  RELOAD_FAIL,
};
