// flow-typed signature: 1eb59008a7cd71f1678be61a1573847e
// flow-typed version: <<STUB>>/@pusher/chatkit_v^0.7.16/flow_v0.67.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@pusher/chatkit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare class PusherUser {
  avatarURL: string;
  // createRoom: (name: string, private: boolean, addUserIds: Array<strings>) => Promise<any>;
  disconnect: () => void;
  fetchMessages: ({ url: string }) => {};
  fetchAttachment: any => void;
  id: number;
  joinRoom: () => {};
  name: string;
  readCursor: any => any;
  // rooms: Array<Room>;
  roomSubscriptions: any;
  sendMessage: ({ text: string, roomId: number }) => {};
  users: Array<any>;
}
