// flow-typed signature: d8f73cfc8a790428c114e90572a70e51
// flow-typed version: <<STUB>>/@pusher/chatkit_v^0.7.12/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@pusher/chatkit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@pusher/chatkit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@pusher/chatkit/dist/react-native/chatkit' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/dist/web/chatkit' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/example/main' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/react-native' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/rollup/react-native' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/rollup/shared' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/rollup/web' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/src/chat-manager' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/src/constants' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/src/current-user' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/src/cursor-store' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/src/cursor-subscription' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/src/cursor' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/src/main' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/src/message-subscription' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/src/message' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/src/parsers' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/src/presence-subscription' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/src/room-store' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/src/room-subscription' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/src/room' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/src/store' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/src/token-provider' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/src/typing-indicators' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/src/user-store' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/src/user-subscription' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/src/user' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/src/utils' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/tests/config/development' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/tests/config/example' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/tests/config/production' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/tests/config/staging' {
  declare module.exports: any;
}

declare module '@pusher/chatkit/tests/main' {
  declare module.exports: any;
}

// Filename aliases
declare module '@pusher/chatkit/dist/react-native/chatkit.js' {
  declare module.exports: $Exports<'@pusher/chatkit/dist/react-native/chatkit'>;
}
declare module '@pusher/chatkit/dist/web/chatkit.js' {
  declare module.exports: $Exports<'@pusher/chatkit/dist/web/chatkit'>;
}
declare module '@pusher/chatkit/example/main.js' {
  declare module.exports: $Exports<'@pusher/chatkit/example/main'>;
}
declare module '@pusher/chatkit/react-native.js' {
  declare module.exports: $Exports<'@pusher/chatkit/react-native'>;
}
declare module '@pusher/chatkit/rollup/react-native.js' {
  declare module.exports: $Exports<'@pusher/chatkit/rollup/react-native'>;
}
declare module '@pusher/chatkit/rollup/shared.js' {
  declare module.exports: $Exports<'@pusher/chatkit/rollup/shared'>;
}
declare module '@pusher/chatkit/rollup/web.js' {
  declare module.exports: $Exports<'@pusher/chatkit/rollup/web'>;
}
declare module '@pusher/chatkit/src/chat-manager.js' {
  declare module.exports: $Exports<'@pusher/chatkit/src/chat-manager'>;
}
declare module '@pusher/chatkit/src/constants.js' {
  declare module.exports: $Exports<'@pusher/chatkit/src/constants'>;
}
declare module '@pusher/chatkit/src/current-user.js' {
  declare module.exports: $Exports<'@pusher/chatkit/src/current-user'>;
}
declare module '@pusher/chatkit/src/cursor-store.js' {
  declare module.exports: $Exports<'@pusher/chatkit/src/cursor-store'>;
}
declare module '@pusher/chatkit/src/cursor-subscription.js' {
  declare module.exports: $Exports<'@pusher/chatkit/src/cursor-subscription'>;
}
declare module '@pusher/chatkit/src/cursor.js' {
  declare module.exports: $Exports<'@pusher/chatkit/src/cursor'>;
}
declare module '@pusher/chatkit/src/main.js' {
  declare module.exports: $Exports<'@pusher/chatkit/src/main'>;
}
declare module '@pusher/chatkit/src/message-subscription.js' {
  declare module.exports: $Exports<'@pusher/chatkit/src/message-subscription'>;
}
declare module '@pusher/chatkit/src/message.js' {
  declare module.exports: $Exports<'@pusher/chatkit/src/message'>;
}
declare module '@pusher/chatkit/src/parsers.js' {
  declare module.exports: $Exports<'@pusher/chatkit/src/parsers'>;
}
declare module '@pusher/chatkit/src/presence-subscription.js' {
  declare module.exports: $Exports<'@pusher/chatkit/src/presence-subscription'>;
}
declare module '@pusher/chatkit/src/room-store.js' {
  declare module.exports: $Exports<'@pusher/chatkit/src/room-store'>;
}
declare module '@pusher/chatkit/src/room-subscription.js' {
  declare module.exports: $Exports<'@pusher/chatkit/src/room-subscription'>;
}
declare module '@pusher/chatkit/src/room.js' {
  declare module.exports: $Exports<'@pusher/chatkit/src/room'>;
}
declare module '@pusher/chatkit/src/store.js' {
  declare module.exports: $Exports<'@pusher/chatkit/src/store'>;
}
declare module '@pusher/chatkit/src/token-provider.js' {
  declare module.exports: $Exports<'@pusher/chatkit/src/token-provider'>;
}
declare module '@pusher/chatkit/src/typing-indicators.js' {
  declare module.exports: $Exports<'@pusher/chatkit/src/typing-indicators'>;
}
declare module '@pusher/chatkit/src/user-store.js' {
  declare module.exports: $Exports<'@pusher/chatkit/src/user-store'>;
}
declare module '@pusher/chatkit/src/user-subscription.js' {
  declare module.exports: $Exports<'@pusher/chatkit/src/user-subscription'>;
}
declare module '@pusher/chatkit/src/user.js' {
  declare module.exports: $Exports<'@pusher/chatkit/src/user'>;
}
declare module '@pusher/chatkit/src/utils.js' {
  declare module.exports: $Exports<'@pusher/chatkit/src/utils'>;
}
declare module '@pusher/chatkit/tests/config/development.js' {
  declare module.exports: $Exports<'@pusher/chatkit/tests/config/development'>;
}
declare module '@pusher/chatkit/tests/config/example.js' {
  declare module.exports: $Exports<'@pusher/chatkit/tests/config/example'>;
}
declare module '@pusher/chatkit/tests/config/production.js' {
  declare module.exports: $Exports<'@pusher/chatkit/tests/config/production'>;
}
declare module '@pusher/chatkit/tests/config/staging.js' {
  declare module.exports: $Exports<'@pusher/chatkit/tests/config/staging'>;
}
declare module '@pusher/chatkit/tests/main.js' {
  declare module.exports: $Exports<'@pusher/chatkit/tests/main'>;
}
