// flow-typed signature: c121e44b2d27a7f45d4d9d598399a7f4
// flow-typed version: <<STUB>>/foect_v^0.1.5/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'foect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'foect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'foect/lib/control' {
  declare module.exports: any;
}

declare module 'foect/lib/form' {
  declare module.exports: any;
}

declare module 'foect/lib/index' {
  declare module.exports: any;
}

declare module 'foect/lib/type' {
  declare module.exports: any;
}

declare module 'foect/lib/utils' {
  declare module.exports: any;
}

declare module 'foect/lib/validators' {
  declare module.exports: any;
}

// Filename aliases
declare module 'foect/lib/control.js' {
  declare module.exports: $Exports<'foect/lib/control'>;
}
declare module 'foect/lib/form.js' {
  declare module.exports: $Exports<'foect/lib/form'>;
}
declare module 'foect/lib/index.js' {
  declare module.exports: $Exports<'foect/lib/index'>;
}
declare module 'foect/lib/type.js' {
  declare module.exports: $Exports<'foect/lib/type'>;
}
declare module 'foect/lib/utils.js' {
  declare module.exports: $Exports<'foect/lib/utils'>;
}
declare module 'foect/lib/validators.js' {
  declare module.exports: $Exports<'foect/lib/validators'>;
}
