// flow-typed signature: d5e8d93b90293ccf1feea08f9d735dcd
// flow-typed version: <<STUB>>/instabug-reactnative_v^2.8.1/flow_v0.67.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'instabug-reactnative'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'instabug-reactnative' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'instabug-reactnative/index' {
  declare module.exports: $Exports<'instabug-reactnative'>;
}
declare module 'instabug-reactnative/index.js' {
  declare module.exports: $Exports<'instabug-reactnative'>;
}
