// flow-typed signature: be819f4b163ec5bedcc9f462db1f18c4
// flow-typed version: <<STUB>>/react-native-image-pan-zoom_v^2.1.4/flow_v0.67.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-image-pan-zoom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-image-pan-zoom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-image-pan-zoom/built/image-zoom/image-zoom.component' {
  declare module.exports: any;
}

declare module 'react-native-image-pan-zoom/built/image-zoom/image-zoom.style' {
  declare module.exports: any;
}

declare module 'react-native-image-pan-zoom/built/image-zoom/image-zoom.type' {
  declare module.exports: any;
}

declare module 'react-native-image-pan-zoom/built/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-image-pan-zoom/built/image-zoom/image-zoom.component.js' {
  declare module.exports: $Exports<'react-native-image-pan-zoom/built/image-zoom/image-zoom.component'>;
}
declare module 'react-native-image-pan-zoom/built/image-zoom/image-zoom.style.js' {
  declare module.exports: $Exports<'react-native-image-pan-zoom/built/image-zoom/image-zoom.style'>;
}
declare module 'react-native-image-pan-zoom/built/image-zoom/image-zoom.type.js' {
  declare module.exports: $Exports<'react-native-image-pan-zoom/built/image-zoom/image-zoom.type'>;
}
declare module 'react-native-image-pan-zoom/built/index.js' {
  declare module.exports: $Exports<'react-native-image-pan-zoom/built/index'>;
}
