// flow-typed signature: 3fd6a525f21c45218a57402d55b615dc
// flow-typed version: <<STUB>>/react-native-micro-animated-button_v^0.0.21/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-micro-animated-button'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-micro-animated-button' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-micro-animated-button/button' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-micro-animated-button/button.js' {
  declare module.exports: $Exports<'react-native-micro-animated-button/button'>;
}
