// flow-typed signature: bcb0f0fd2bcf5873ee0eb78293030d20
// flow-typed version: <<STUB>>/react-native-touch-visualizer_v^0.1.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-touch-visualizer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-touch-visualizer' {
  declare module.exports: any;
}
