// flow-typed signature: ac2807ab7212b32f7e3f67fdf486297d
// flow-typed version: <<STUB>>/react-native-flip-card_v^3.5.2/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-flip-card'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-flip-card' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-flip-card/lib/FlipCard' {
  declare module.exports: any;
}

declare module 'react-native-flip-card/lib/Style' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-flip-card/index' {
  declare module.exports: $Exports<'react-native-flip-card'>;
}
declare module 'react-native-flip-card/index.js' {
  declare module.exports: $Exports<'react-native-flip-card'>;
}
declare module 'react-native-flip-card/lib/FlipCard.js' {
  declare module.exports: $Exports<'react-native-flip-card/lib/FlipCard'>;
}
declare module 'react-native-flip-card/lib/Style.js' {
  declare module.exports: $Exports<'react-native-flip-card/lib/Style'>;
}
