// flow-typed signature: 7d17bc711ecb51d4da48e74f63098fca
// flow-typed version: <<STUB>>/react-native-simple-radio-button_v^2.7.1/flow_v0.67.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-simple-radio-button'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-simple-radio-button' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-simple-radio-button/lib/SimpleRadioButton' {
  declare module.exports: any;
}

declare module 'react-native-simple-radio-button/lib/Style' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-simple-radio-button/index' {
  declare module.exports: $Exports<'react-native-simple-radio-button'>;
}
declare module 'react-native-simple-radio-button/index.js' {
  declare module.exports: $Exports<'react-native-simple-radio-button'>;
}
declare module 'react-native-simple-radio-button/lib/SimpleRadioButton.js' {
  declare module.exports: $Exports<'react-native-simple-radio-button/lib/SimpleRadioButton'>;
}
declare module 'react-native-simple-radio-button/lib/Style.js' {
  declare module.exports: $Exports<'react-native-simple-radio-button/lib/Style'>;
}
