// flow-typed signature: ae6f689cdf7ffe0f2b3a270bcf5d61be
// flow-typed version: <<STUB>>/react-native-mentions_v^1.1.4/flow_v0.67.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-mentions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-mentions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-mentions/sample/__tests__/index.android' {
  declare module.exports: any;
}

declare module 'react-native-mentions/sample/__tests__/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-mentions/sample/index' {
  declare module.exports: any;
}

declare module 'react-native-mentions/sample/service' {
  declare module.exports: any;
}

declare module 'react-native-mentions/src/MentionsTextInput' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-mentions/index' {
  declare module.exports: $Exports<'react-native-mentions'>;
}
declare module 'react-native-mentions/index.js' {
  declare module.exports: $Exports<'react-native-mentions'>;
}
declare module 'react-native-mentions/sample/__tests__/index.android.js' {
  declare module.exports: $Exports<'react-native-mentions/sample/__tests__/index.android'>;
}
declare module 'react-native-mentions/sample/__tests__/index.ios.js' {
  declare module.exports: $Exports<'react-native-mentions/sample/__tests__/index.ios'>;
}
declare module 'react-native-mentions/sample/index.js' {
  declare module.exports: $Exports<'react-native-mentions/sample/index'>;
}
declare module 'react-native-mentions/sample/service.js' {
  declare module.exports: $Exports<'react-native-mentions/sample/service'>;
}
declare module 'react-native-mentions/src/MentionsTextInput.js' {
  declare module.exports: $Exports<'react-native-mentions/src/MentionsTextInput'>;
}
