// flow-typed signature: 084d049d60821c8fc9400f76530cc488
// flow-typed version: <<STUB>>/react-native-gifted-chat_v^0.3.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-gifted-chat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-gifted-chat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-gifted-chat/src/Actions' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/Avatar' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/Bubble' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/Composer' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/Day' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/GiftedAvatar' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/GiftedChat' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/GiftedChatInteractionManager' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/InputToolbar' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/LoadEarlier' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/Message' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/MessageContainer' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/MessageImage' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/MessageText' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/Send' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/SystemMessage' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/Time' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-gifted-chat/index' {
  declare module.exports: $Exports<'react-native-gifted-chat'>;
}
declare module 'react-native-gifted-chat/index.js' {
  declare module.exports: $Exports<'react-native-gifted-chat'>;
}
declare module 'react-native-gifted-chat/src/Actions.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/Actions'>;
}
declare module 'react-native-gifted-chat/src/Avatar.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/Avatar'>;
}
declare module 'react-native-gifted-chat/src/Bubble.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/Bubble'>;
}
declare module 'react-native-gifted-chat/src/Composer.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/Composer'>;
}
declare module 'react-native-gifted-chat/src/Day.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/Day'>;
}
declare module 'react-native-gifted-chat/src/GiftedAvatar.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/GiftedAvatar'>;
}
declare module 'react-native-gifted-chat/src/GiftedChat.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/GiftedChat'>;
}
declare module 'react-native-gifted-chat/src/GiftedChatInteractionManager.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/GiftedChatInteractionManager'>;
}
declare module 'react-native-gifted-chat/src/InputToolbar.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/InputToolbar'>;
}
declare module 'react-native-gifted-chat/src/LoadEarlier.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/LoadEarlier'>;
}
declare module 'react-native-gifted-chat/src/Message.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/Message'>;
}
declare module 'react-native-gifted-chat/src/MessageContainer.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/MessageContainer'>;
}
declare module 'react-native-gifted-chat/src/MessageImage.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/MessageImage'>;
}
declare module 'react-native-gifted-chat/src/MessageText.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/MessageText'>;
}
declare module 'react-native-gifted-chat/src/Send.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/Send'>;
}
declare module 'react-native-gifted-chat/src/SystemMessage.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/SystemMessage'>;
}
declare module 'react-native-gifted-chat/src/Time.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/Time'>;
}
declare module 'react-native-gifted-chat/src/utils.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/utils'>;
}
