// flow-typed signature: 56dff373bbb74955ca328aee565c29c0
// flow-typed version: <<STUB>>/react-native-gifted-chat_v^0.4.3/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-gifted-chat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-gifted-chat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-gifted-chat/src/__tests__/Actions.test' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/__tests__/Avatar.test' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/__tests__/Bubble.test' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/__tests__/Color.test' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/__tests__/Composer.test' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/__tests__/Constant.test' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/__tests__/Day.test' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/__tests__/GiftedAvatar.test' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/__tests__/GiftedChat.test' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/__tests__/InputToolbar.test' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/__tests__/LoadEarlier.test' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/__tests__/Message.test' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/__tests__/MessageContainer.test' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/__tests__/MessageImage.test' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/__tests__/MessageText.test' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/__tests__/Send.test' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/__tests__/SystemMessage.test' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/__tests__/Time.test' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/Actions' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/Avatar' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/Bubble' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/Color' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/Composer' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/Constant' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/Day' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/GiftedAvatar' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/GiftedChat' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/GiftedChatInteractionManager' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/InputToolbar' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/LoadEarlier' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/Message' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/MessageContainer' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/MessageImage' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/MessageText' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/Send' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/SystemMessage' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/Time' {
  declare module.exports: any;
}

declare module 'react-native-gifted-chat/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-gifted-chat/index' {
  declare module.exports: $Exports<'react-native-gifted-chat'>;
}
declare module 'react-native-gifted-chat/index.js' {
  declare module.exports: $Exports<'react-native-gifted-chat'>;
}
declare module 'react-native-gifted-chat/src/__tests__/Actions.test.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/__tests__/Actions.test'>;
}
declare module 'react-native-gifted-chat/src/__tests__/Avatar.test.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/__tests__/Avatar.test'>;
}
declare module 'react-native-gifted-chat/src/__tests__/Bubble.test.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/__tests__/Bubble.test'>;
}
declare module 'react-native-gifted-chat/src/__tests__/Color.test.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/__tests__/Color.test'>;
}
declare module 'react-native-gifted-chat/src/__tests__/Composer.test.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/__tests__/Composer.test'>;
}
declare module 'react-native-gifted-chat/src/__tests__/Constant.test.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/__tests__/Constant.test'>;
}
declare module 'react-native-gifted-chat/src/__tests__/Day.test.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/__tests__/Day.test'>;
}
declare module 'react-native-gifted-chat/src/__tests__/GiftedAvatar.test.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/__tests__/GiftedAvatar.test'>;
}
declare module 'react-native-gifted-chat/src/__tests__/GiftedChat.test.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/__tests__/GiftedChat.test'>;
}
declare module 'react-native-gifted-chat/src/__tests__/InputToolbar.test.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/__tests__/InputToolbar.test'>;
}
declare module 'react-native-gifted-chat/src/__tests__/LoadEarlier.test.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/__tests__/LoadEarlier.test'>;
}
declare module 'react-native-gifted-chat/src/__tests__/Message.test.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/__tests__/Message.test'>;
}
declare module 'react-native-gifted-chat/src/__tests__/MessageContainer.test.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/__tests__/MessageContainer.test'>;
}
declare module 'react-native-gifted-chat/src/__tests__/MessageImage.test.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/__tests__/MessageImage.test'>;
}
declare module 'react-native-gifted-chat/src/__tests__/MessageText.test.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/__tests__/MessageText.test'>;
}
declare module 'react-native-gifted-chat/src/__tests__/Send.test.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/__tests__/Send.test'>;
}
declare module 'react-native-gifted-chat/src/__tests__/SystemMessage.test.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/__tests__/SystemMessage.test'>;
}
declare module 'react-native-gifted-chat/src/__tests__/Time.test.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/__tests__/Time.test'>;
}
declare module 'react-native-gifted-chat/src/Actions.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/Actions'>;
}
declare module 'react-native-gifted-chat/src/Avatar.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/Avatar'>;
}
declare module 'react-native-gifted-chat/src/Bubble.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/Bubble'>;
}
declare module 'react-native-gifted-chat/src/Color.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/Color'>;
}
declare module 'react-native-gifted-chat/src/Composer.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/Composer'>;
}
declare module 'react-native-gifted-chat/src/Constant.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/Constant'>;
}
declare module 'react-native-gifted-chat/src/Day.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/Day'>;
}
declare module 'react-native-gifted-chat/src/GiftedAvatar.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/GiftedAvatar'>;
}
declare module 'react-native-gifted-chat/src/GiftedChat.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/GiftedChat'>;
}
declare module 'react-native-gifted-chat/src/GiftedChatInteractionManager.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/GiftedChatInteractionManager'>;
}
declare module 'react-native-gifted-chat/src/InputToolbar.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/InputToolbar'>;
}
declare module 'react-native-gifted-chat/src/LoadEarlier.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/LoadEarlier'>;
}
declare module 'react-native-gifted-chat/src/Message.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/Message'>;
}
declare module 'react-native-gifted-chat/src/MessageContainer.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/MessageContainer'>;
}
declare module 'react-native-gifted-chat/src/MessageImage.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/MessageImage'>;
}
declare module 'react-native-gifted-chat/src/MessageText.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/MessageText'>;
}
declare module 'react-native-gifted-chat/src/Send.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/Send'>;
}
declare module 'react-native-gifted-chat/src/SystemMessage.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/SystemMessage'>;
}
declare module 'react-native-gifted-chat/src/Time.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/Time'>;
}
declare module 'react-native-gifted-chat/src/utils.js' {
  declare module.exports: $Exports<'react-native-gifted-chat/src/utils'>;
}
