// flow-typed signature: d2cc02f8abffd6027c1d69fdb571e64f
// flow-typed version: <<STUB>>/react-native-onboarding-swiper_v^0.7.1/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-onboarding-swiper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-onboarding-swiper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-onboarding-swiper/src/buttons/DoneButton' {
  declare module.exports: any;
}

declare module 'react-native-onboarding-swiper/src/buttons/NextButton' {
  declare module.exports: any;
}

declare module 'react-native-onboarding-swiper/src/buttons/SkipButton' {
  declare module.exports: any;
}

declare module 'react-native-onboarding-swiper/src/buttons/SymbolButton' {
  declare module.exports: any;
}

declare module 'react-native-onboarding-swiper/src/buttons/TextButton' {
  declare module.exports: any;
}

declare module 'react-native-onboarding-swiper/src/buttons/util' {
  declare module.exports: any;
}

declare module 'react-native-onboarding-swiper/src/Dot' {
  declare module.exports: any;
}

declare module 'react-native-onboarding-swiper/src/Dots' {
  declare module.exports: any;
}

declare module 'react-native-onboarding-swiper/src/index' {
  declare module.exports: any;
}

declare module 'react-native-onboarding-swiper/src/Page' {
  declare module.exports: any;
}

declare module 'react-native-onboarding-swiper/src/Pagination' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-onboarding-swiper/src/buttons/DoneButton.js' {
  declare module.exports: $Exports<'react-native-onboarding-swiper/src/buttons/DoneButton'>;
}
declare module 'react-native-onboarding-swiper/src/buttons/NextButton.js' {
  declare module.exports: $Exports<'react-native-onboarding-swiper/src/buttons/NextButton'>;
}
declare module 'react-native-onboarding-swiper/src/buttons/SkipButton.js' {
  declare module.exports: $Exports<'react-native-onboarding-swiper/src/buttons/SkipButton'>;
}
declare module 'react-native-onboarding-swiper/src/buttons/SymbolButton.js' {
  declare module.exports: $Exports<'react-native-onboarding-swiper/src/buttons/SymbolButton'>;
}
declare module 'react-native-onboarding-swiper/src/buttons/TextButton.js' {
  declare module.exports: $Exports<'react-native-onboarding-swiper/src/buttons/TextButton'>;
}
declare module 'react-native-onboarding-swiper/src/buttons/util.js' {
  declare module.exports: $Exports<'react-native-onboarding-swiper/src/buttons/util'>;
}
declare module 'react-native-onboarding-swiper/src/Dot.js' {
  declare module.exports: $Exports<'react-native-onboarding-swiper/src/Dot'>;
}
declare module 'react-native-onboarding-swiper/src/Dots.js' {
  declare module.exports: $Exports<'react-native-onboarding-swiper/src/Dots'>;
}
declare module 'react-native-onboarding-swiper/src/index.js' {
  declare module.exports: $Exports<'react-native-onboarding-swiper/src/index'>;
}
declare module 'react-native-onboarding-swiper/src/Page.js' {
  declare module.exports: $Exports<'react-native-onboarding-swiper/src/Page'>;
}
declare module 'react-native-onboarding-swiper/src/Pagination.js' {
  declare module.exports: $Exports<'react-native-onboarding-swiper/src/Pagination'>;
}
