// flow-typed signature: cd1eb9f89e47ef1ec5fdd44bbb33d15f
// flow-typed version: <<STUB>>/react-native-keyboard-accessory_v^0.1.2/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-keyboard-accessory'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-keyboard-accessory' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-keyboard-accessory/components/AccessoryArrowButton/index' {
  declare module.exports: any;
}

declare module 'react-native-keyboard-accessory/components/Arrow/index' {
  declare module.exports: any;
}

declare module 'react-native-keyboard-accessory/KeyboardAccessoryNavigation' {
  declare module.exports: any;
}

declare module 'react-native-keyboard-accessory/KeyboardAccessoryView' {
  declare module.exports: any;
}

declare module 'react-native-keyboard-accessory/KeyboardAwareTabBarComponent' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-keyboard-accessory/components/AccessoryArrowButton/index.js' {
  declare module.exports: $Exports<'react-native-keyboard-accessory/components/AccessoryArrowButton/index'>;
}
declare module 'react-native-keyboard-accessory/components/Arrow/index.js' {
  declare module.exports: $Exports<'react-native-keyboard-accessory/components/Arrow/index'>;
}
declare module 'react-native-keyboard-accessory/index' {
  declare module.exports: $Exports<'react-native-keyboard-accessory'>;
}
declare module 'react-native-keyboard-accessory/index.js' {
  declare module.exports: $Exports<'react-native-keyboard-accessory'>;
}
declare module 'react-native-keyboard-accessory/KeyboardAccessoryNavigation.js' {
  declare module.exports: $Exports<'react-native-keyboard-accessory/KeyboardAccessoryNavigation'>;
}
declare module 'react-native-keyboard-accessory/KeyboardAccessoryView.js' {
  declare module.exports: $Exports<'react-native-keyboard-accessory/KeyboardAccessoryView'>;
}
declare module 'react-native-keyboard-accessory/KeyboardAwareTabBarComponent.js' {
  declare module.exports: $Exports<'react-native-keyboard-accessory/KeyboardAwareTabBarComponent'>;
}
