// flow-typed signature: e420947e4adff81db8f5c3c6b2b657d1
// flow-typed version: <<STUB>>/react-native-tensorflow_v^0.1.7/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-tensorflow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-tensorflow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-tensorflow/index' {
  declare module.exports: $Exports<'react-native-tensorflow'>;
}
declare module 'react-native-tensorflow/index.js' {
  declare module.exports: $Exports<'react-native-tensorflow'>;
}
