// flow-typed signature: 2938f878c1e66ac415dc97f853f20c15
// flow-typed version: <<STUB>>/react-native-fast-image_v^2.0.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-fast-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-fast-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-fast-image/FastImage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-fast-image/FastImage.js' {
  declare module.exports: $Exports<'react-native-fast-image/FastImage'>;
}
