// flow-typed signature: 47eda37f8488f968fa7d7059cc814567
// flow-typed version: <<STUB>>/react-native-star-rating_v^1.0.9/flow_v0.67.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-star-rating'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-star-rating' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-star-rating/StarButton' {
  declare module.exports: any;
}

declare module 'react-native-star-rating/StarRating' {
  declare module.exports: any;
}

declare module 'react-native-star-rating/tests/StarButton.test' {
  declare module.exports: any;
}

declare module 'react-native-star-rating/tests/StarRating.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-star-rating/index' {
  declare module.exports: $Exports<'react-native-star-rating'>;
}
declare module 'react-native-star-rating/index.js' {
  declare module.exports: $Exports<'react-native-star-rating'>;
}
declare module 'react-native-star-rating/StarButton.js' {
  declare module.exports: $Exports<'react-native-star-rating/StarButton'>;
}
declare module 'react-native-star-rating/StarRating.js' {
  declare module.exports: $Exports<'react-native-star-rating/StarRating'>;
}
declare module 'react-native-star-rating/tests/StarButton.test.js' {
  declare module.exports: $Exports<'react-native-star-rating/tests/StarButton.test'>;
}
declare module 'react-native-star-rating/tests/StarRating.test.js' {
  declare module.exports: $Exports<'react-native-star-rating/tests/StarRating.test'>;
}
