// flow-typed signature: 3fd312be0d6a2bd77216f8247932626d
// flow-typed version: <<STUB>>/react-native-collapsible_v^0.10.0/flow_v0.67.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-collapsible'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-collapsible' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-collapsible/Accordion' {
  declare module.exports: any;
}

declare module 'react-native-collapsible/Collapsible' {
  declare module.exports: any;
}

declare module 'react-native-collapsible/config/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-collapsible/Accordion.js' {
  declare module.exports: $Exports<'react-native-collapsible/Accordion'>;
}
declare module 'react-native-collapsible/Collapsible.js' {
  declare module.exports: $Exports<'react-native-collapsible/Collapsible'>;
}
declare module 'react-native-collapsible/config/index.js' {
  declare module.exports: $Exports<'react-native-collapsible/config/index'>;
}
