// flow-typed signature: cdde7b34081e39aba4be9d35c6a9dadc
// flow-typed version: <<STUB>>/react-native-android-location-enabler_v1.0.6/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-android-location-enabler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-android-location-enabler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-android-location-enabler/index' {
  declare module.exports: $Exports<'react-native-android-location-enabler'>;
}
declare module 'react-native-android-location-enabler/index.js' {
  declare module.exports: $Exports<'react-native-android-location-enabler'>;
}
