// flow-typed signature: 512145c6b9bbdecdf3f99eb5dee1f7bd
// flow-typed version: <<STUB>>/react-native-keyboard-accessory_v^0.0.9/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-keyboard-accessory'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-keyboard-accessory' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-keyboard-accessory/lib/components/AccessoryArrowButton/index' {
  declare module.exports: any;
}

declare module 'react-native-keyboard-accessory/lib/components/Arrow/index' {
  declare module.exports: any;
}

declare module 'react-native-keyboard-accessory/lib/KeyboardAccessoryNavigation' {
  declare module.exports: any;
}

declare module 'react-native-keyboard-accessory/lib/KeyboardAccessoryView' {
  declare module.exports: any;
}

declare module 'react-native-keyboard-accessory/lib/KeyboardAwareTabBarComponent' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-keyboard-accessory/index' {
  declare module.exports: $Exports<'react-native-keyboard-accessory'>;
}
declare module 'react-native-keyboard-accessory/index.js' {
  declare module.exports: $Exports<'react-native-keyboard-accessory'>;
}
declare module 'react-native-keyboard-accessory/lib/components/AccessoryArrowButton/index.js' {
  declare module.exports: $Exports<'react-native-keyboard-accessory/lib/components/AccessoryArrowButton/index'>;
}
declare module 'react-native-keyboard-accessory/lib/components/Arrow/index.js' {
  declare module.exports: $Exports<'react-native-keyboard-accessory/lib/components/Arrow/index'>;
}
declare module 'react-native-keyboard-accessory/lib/KeyboardAccessoryNavigation.js' {
  declare module.exports: $Exports<'react-native-keyboard-accessory/lib/KeyboardAccessoryNavigation'>;
}
declare module 'react-native-keyboard-accessory/lib/KeyboardAccessoryView.js' {
  declare module.exports: $Exports<'react-native-keyboard-accessory/lib/KeyboardAccessoryView'>;
}
declare module 'react-native-keyboard-accessory/lib/KeyboardAwareTabBarComponent.js' {
  declare module.exports: $Exports<'react-native-keyboard-accessory/lib/KeyboardAwareTabBarComponent'>;
}
