// flow-typed signature: 9b75c9127c28fcd5f4e13391b4296920
// flow-typed version: <<STUB>>/react-native-credit-card-input_v^0.4.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-credit-card-input'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-credit-card-input' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-credit-card-input/src/CardView' {
  declare module.exports: any;
}

declare module 'react-native-credit-card-input/src/CCFieldFormatter' {
  declare module.exports: any;
}

declare module 'react-native-credit-card-input/src/CCFieldValidator' {
  declare module.exports: any;
}

declare module 'react-native-credit-card-input/src/CCInput' {
  declare module.exports: any;
}

declare module 'react-native-credit-card-input/src/connectToState' {
  declare module.exports: any;
}

declare module 'react-native-credit-card-input/src/CreditCardInput' {
  declare module.exports: any;
}

declare module 'react-native-credit-card-input/src/Icons' {
  declare module.exports: any;
}

declare module 'react-native-credit-card-input/src/index' {
  declare module.exports: any;
}

declare module 'react-native-credit-card-input/src/LiteCreditCardInput' {
  declare module.exports: any;
}

declare module 'react-native-credit-card-input/src/Utilities' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-credit-card-input/index' {
  declare module.exports: $Exports<'react-native-credit-card-input'>;
}
declare module 'react-native-credit-card-input/index.js' {
  declare module.exports: $Exports<'react-native-credit-card-input'>;
}
declare module 'react-native-credit-card-input/src/CardView.js' {
  declare module.exports: $Exports<'react-native-credit-card-input/src/CardView'>;
}
declare module 'react-native-credit-card-input/src/CCFieldFormatter.js' {
  declare module.exports: $Exports<'react-native-credit-card-input/src/CCFieldFormatter'>;
}
declare module 'react-native-credit-card-input/src/CCFieldValidator.js' {
  declare module.exports: $Exports<'react-native-credit-card-input/src/CCFieldValidator'>;
}
declare module 'react-native-credit-card-input/src/CCInput.js' {
  declare module.exports: $Exports<'react-native-credit-card-input/src/CCInput'>;
}
declare module 'react-native-credit-card-input/src/connectToState.js' {
  declare module.exports: $Exports<'react-native-credit-card-input/src/connectToState'>;
}
declare module 'react-native-credit-card-input/src/CreditCardInput.js' {
  declare module.exports: $Exports<'react-native-credit-card-input/src/CreditCardInput'>;
}
declare module 'react-native-credit-card-input/src/Icons.js' {
  declare module.exports: $Exports<'react-native-credit-card-input/src/Icons'>;
}
declare module 'react-native-credit-card-input/src/index.js' {
  declare module.exports: $Exports<'react-native-credit-card-input/src/index'>;
}
declare module 'react-native-credit-card-input/src/LiteCreditCardInput.js' {
  declare module.exports: $Exports<'react-native-credit-card-input/src/LiteCreditCardInput'>;
}
declare module 'react-native-credit-card-input/src/Utilities.js' {
  declare module.exports: $Exports<'react-native-credit-card-input/src/Utilities'>;
}
