// flow-typed signature: cd6a2411c0fba54ed9d5d6a82fd00093
// flow-typed version: <<STUB>>/react-native-circular-progress_v^0.2.0/flow_v0.67.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-circular-progress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-circular-progress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-circular-progress/src/AnimatedCircularProgress' {
  declare module.exports: any;
}

declare module 'react-native-circular-progress/src/CircularProgress' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-circular-progress/index' {
  declare module.exports: $Exports<'react-native-circular-progress'>;
}
declare module 'react-native-circular-progress/index.js' {
  declare module.exports: $Exports<'react-native-circular-progress'>;
}
declare module 'react-native-circular-progress/src/AnimatedCircularProgress.js' {
  declare module.exports: $Exports<'react-native-circular-progress/src/AnimatedCircularProgress'>;
}
declare module 'react-native-circular-progress/src/CircularProgress.js' {
  declare module.exports: $Exports<'react-native-circular-progress/src/CircularProgress'>;
}
