// flow-typed signature: 10a134568ba95f5c34d893e31f877f6a
// flow-typed version: <<STUB>>/react-native-analytics-segment-io_v^3.1.3/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-analytics-segment-io'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-analytics-segment-io' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-analytics-segment-io/android/build/intermediates/exploded-aar/com.appboy/android-sdk-ui/2.1.2/assets/appboy-html-in-app-message-javascript-component' {
  declare module.exports: any;
}

declare module 'react-native-analytics-segment-io/android/build/intermediates/exploded-aar/com.appboy/android-sdk-ui/2.2.1/assets/appboy-html-in-app-message-javascript-component' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-analytics-segment-io/android/build/intermediates/exploded-aar/com.appboy/android-sdk-ui/2.1.2/assets/appboy-html-in-app-message-javascript-component.js' {
  declare module.exports: $Exports<'react-native-analytics-segment-io/android/build/intermediates/exploded-aar/com.appboy/android-sdk-ui/2.1.2/assets/appboy-html-in-app-message-javascript-component'>;
}
declare module 'react-native-analytics-segment-io/android/build/intermediates/exploded-aar/com.appboy/android-sdk-ui/2.2.1/assets/appboy-html-in-app-message-javascript-component.js' {
  declare module.exports: $Exports<'react-native-analytics-segment-io/android/build/intermediates/exploded-aar/com.appboy/android-sdk-ui/2.2.1/assets/appboy-html-in-app-message-javascript-component'>;
}
declare module 'react-native-analytics-segment-io/index' {
  declare module.exports: $Exports<'react-native-analytics-segment-io'>;
}
declare module 'react-native-analytics-segment-io/index.js' {
  declare module.exports: $Exports<'react-native-analytics-segment-io'>;
}
