// flow-typed signature: 4f97009ed346bd73fb1576ce0447b37f
// flow-typed version: <<STUB>>/@babel/plugin-transform-react-jsx-source_v^7.0.0-beta.52/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-react-jsx-source'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-transform-react-jsx-source' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-transform-react-jsx-source/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-transform-react-jsx-source/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-react-jsx-source/lib/index'>;
}
