# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

project 'onova.xcodeproj'

target 'onova' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for onova
  pod 'Firebase/Core'
  # pod 'GoogleSignIn'

  target 'onova-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

    pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'


  end

  target 'onovaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
