// @flow

export default {
  MIN_LENGTH_DESCRIPTION: 7,
  MAX_LENGTH_DESCRIPTION: 300,
  MAX_LENGTH_COMMENT: 300,
  MAX_LENGTH_REVIEW: 500,
  MAX_CHAT_INPUT_LENGTH: 200,
  MIN_LENGTH_REVIEW: 10,
  MIN_LENGTH_PER_TAG: 2,
  MAX_LENGTH_PER_TAG: 30,
  MIN_TAGS: 0,
  // MAX_TAGS: 30,
  USERNAME_REGEX: /^[a-zA-Z0-9\_\.]+$/,
  HASHTAG_REGEX: /^[a-zA-Z0-9]+$/,
  SENDBIRD_APP_ID: '***REMOVED***',
  INSTABUG_TOKEN: '***REMOVED***',
  // BRAINTREE_TOKENIZATION_KEY: 'sandbox_45rbtwk4_wpk6jkwxv5kpqp58',
};
