// @flow

export default {
  MAX_LENGTH_DESCRIPTION: 300,
  MAX_LENGTH_COMMENT: 300,
  MAX_CHAT_INPUT_LENGTH: 200,
  USERNAME_REGEX: /^[a-zA-Z0-9\_\.]*$/,
  SENDBIRD_APP_ID: '***REMOVED***',
  INSTABUG_TOKEN: '***REMOVED***',
  // BRAINTREE_TOKENIZATION_KEY: 'sandbox_45rbtwk4_wpk6jkwxv5kpqp58',
};
